### PR TITLE
Adding GoPollGo

### PR DESCRIPTION
**Pull request by Bensign**
Let me know if you need anything else.  Thanks!

### CODE REVIEW

**Comment by daniellevine** [comment]
Do you have a png logo of the appropriate size? I'm going to make some small tweaks (move Rackspace info down to business software and issue a pull), but otherwise looks good.

**Comment by Bensign** [comment]
Does this work?

GoPollGo Logo

**Comment by daniellevine** [comment]
Do you have any transparent pngs that go on a white background? Sizing info is on weusethat github page

**Comment by Bensign** [comment]
Ah, didn't even see that.  Yes, I can get one.  Get it to you in the morning?  Just realized I lost Photoshop when I reformatted my machine yesterday.

**Comment by daniellevine** [comment]
Sure, the post is ready to go if you accept my pull and then just the logo
and I can go live!

I'll have to rake the tags but that's easy enough :)

On Wed, Aug 8, 2012 at 12:49 AM, Ben Schaechter notifications@github.comwrote:

> Ah, didn't even see that. Yes, I can get one. Get it to you in the
> morning? Just realized I lost Photoshop when I reformatted my machine
> yesterday.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/weusethat/we-use-that/pull/6#issuecomment-7577240.

## 

Dan

@daniel_levine

**Pull request merged**
